# Gitpod Configuration for Expo + React Native Development
# This enables full web-based development without any local setup

image:
  file: .gitpod.Dockerfile

ports:
  - port: 8081
    onOpen: open-preview
    description: "Expo Dev Server (Web Preview)"
  - port: 19000
    onOpen: ignore
    description: "Expo Metro Bundler"
  - port: 19001
    onOpen: ignore
    description: "Expo Debugger"

tasks:
  - name: Install Dependencies
    init: |
      echo "Installing Bun and dependencies..."
      curl -fsSL https://bun.sh/install | bash
      export PATH="$HOME/.bun/bin:$PATH"
      bun install
      echo "✅ Dependencies installed!"
    command: echo "Ready to develop! Run 'expo start' in the terminal."

  - name: Start Expo Dev Server (Ready)
    command: |
      export PATH="$HOME/.bun/bin:$PATH"
      echo "Starting Expo development server..."
      echo "📱 QR Code will appear below - scan with Expo Go app"
      bun start

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "esbenp.prettier-vscode"
    - "expo.vscode-expo"
    - "orta.vscode-twoslash-queries"

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addComment: true
    addBadge: true
